######################################################################
# Automatically generated by qmake (2.01a) Tue Mar 13 20:33:41 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += helpui.h mainwindow.h mediafile.h ui_mainwindow.h ui_helpdialog.h
FORMS += helpdialog.ui mainwindow.ui
SOURCES += helpdialog.cpp main.cpp mainwindow.cpp mediafile.cpp
QT += phonon
